module.exports = {
  apps: [
    {
      name: 'mockeleon-api-4000',
      script: './dist/index.js',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 4000,
      },
      error_file: './logs/pm2-4000-error.log',
      out_file: './logs/pm2-4000-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      kill_timeout: 5000,
      listen_timeout: 3000,
      min_uptime: 10000,
      max_restarts: 10,
    },
    {
      name: 'mockeleon-api-4001',
      script: './dist/index.js',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 4001,
      },
      error_file: './logs/pm2-4001-error.log',
      out_file: './logs/pm2-4001-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      kill_timeout: 5000,
      listen_timeout: 3000,
      min_uptime: 10000,
      max_restarts: 10,
    },
    {
      name: 'mockeleon-api-4002',
      script: './dist/index.js',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 4002,
      },
      error_file: './logs/pm2-4002-error.log',
      out_file: './logs/pm2-4002-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      kill_timeout: 5000,
      listen_timeout: 3000,
      min_uptime: 10000,
      max_restarts: 10,
    },
    {
      name: 'mockeleon-api-4003',
      script: './dist/index.js',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 4003,
      },
      error_file: './logs/pm2-4003-error.log',
      out_file: './logs/pm2-4003-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      kill_timeout: 5000,
      listen_timeout: 3000,
      min_uptime: 10000,
      max_restarts: 10,
    },
  ],
};
